  #  Grafana
  ## Dashboarding
  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana-vhv
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=novatec-dashboardsync-datasource
      - SSH_KNOWN_HOSTS=github.com
      - GF_ALLOWED_ORIGINS="http://localhost:3000"
    volumes:
      - /home/atm/Code/vhv:/var/lib/grafana/plugins
      - /home/atm/.ssh/clumsy:/usr/share/grafana/.ssh

        #      - ./grafana/provisioning/home-dashboard/home.json:/usr/share/grafana/public/dashboards/home.json
    ports:
      - 3001:3000
